---

- name: Add the LDAP ACLs
  become: true
  ldap_attrs:
    dn: "olcDatabase={{ '{' }}{{ ldap_db_number }}{{ '}' }}{{ ldap_dbtype|default('hdb') }},cn=config"
    state: exact
    attributes: 
      olcAccess: "{{ ldap_acls }}"
